# Generated by Django 5.2.14 on 2026-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projecttitlealias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDomainLock',
            fields=[
                ('domain', models.CharField(max_length=253, primary_key=True, serialize=False)),
            ],
        ),
    ]
