# Generated by Django 5.2.14 on 2026-09-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_projectdomainlock'),
    ]

    operations = [
        # Keep the unused table during the rolling deployment: old web/worker
        # replicas can still reference it until their replacement is complete.
        # No project data is modified and migration history remains intact.
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name='ProjectDomainLock')],
            database_operations=[],
        ),
    ]
