# Generated by Django 5.2.7 on 2025-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('TUTORIAL', 'TUTORIAL'), ('INTERVIEW', 'INTERVIEW'), ('UPDATE', 'UPDATE'), ('ARTICLE', 'ARTICLE')], default='TUTORIAL', max_length=15),
        ),
    ]
