FROM python:3.13

WORKDIR /app

ARG REQUIREMENTS_FILE=requirements.txt
COPY requirements.txt ./
COPY ${REQUIREMENTS_FILE} ./
RUN pip install --upgrade pip && pip install --no-cache-dir -r "$REQUIREMENTS_FILE"

COPY . .
