# Generated by Django 5.2.14 on 2026-05-26 12:32

import developers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='timezone',
            field=models.CharField(choices=developers.models.get_timezone_choices, default='UTC', max_length=32),
        ),
    ]
