"""
Django settings for builtwithdjango project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import logging
import os

import cloudinary
import environ
import logfire
import posthog
import sentry_sdk
import structlog
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.pydantic_ai import PydanticAIIntegration
from sentry_sdk.integrations.redis import RedisIntegration
from structlog_sentry import SentryProcessor

from builtwithdjango.analytics import posthog_before_send, posthog_extra_tags, posthog_request_filter
from builtwithdjango.logging_utils import scrubbing_callback

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
)
# reading .env file
environ.Env.read_env()

ENVIRONMENT = env("ENV")

SENTRY_DSN = env("SENTRY_DSN", default=env("dsn", default=""))
SENTRY_ENABLED = bool(SENTRY_DSN) and env.bool("SENTRY_ENABLED", default=ENVIRONMENT == "prod")

LOGFIRE_TOKEN = env("LOGFIRE_TOKEN", default="")

if LOGFIRE_TOKEN != "":
    logfire.configure(
        environment=ENVIRONMENT,
        scrubbing=logfire.ScrubbingOptions(callback=scrubbing_callback),
    )


def env_csv(name, default=None):
    raw_value = env(name, default=None)
    if raw_value in (None, ""):
        return list(default or [])
    return [item.strip() for item in raw_value.split(",") if item.strip()]


def env_log_level(name, default):
    raw_value = env(name, default="")
    if raw_value == "":
        return default
    try:
        return int(raw_value)
    except (TypeError, ValueError):
        pass
    return getattr(logging, raw_value.upper(), default)


def env_sample_rate(name, default):
    raw_value = env(name, default=default)
    if raw_value in (None, ""):
        raw_value = default
    return max(0.0, min(1.0, float(raw_value)))


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# False if not in os.environ
DEBUG = env.bool("DEBUG")

SITE_URL = env("SITE_URL")

SENTRY_RELEASE = env("SENTRY_RELEASE", default=env("RENDER_GIT_COMMIT", default=None))
SENTRY_DIST = env("SENTRY_DIST", default=None)
SENTRY_SERVER_NAME = env("SENTRY_SERVER_NAME", default=env("RENDER_SERVICE_NAME", default=None))
SENTRY_ERROR_SAMPLE_RATE = env_sample_rate("SENTRY_ERROR_SAMPLE_RATE", 1.0)
SENTRY_TRACES_SAMPLE_RATE = env_sample_rate("SENTRY_TRACES_SAMPLE_RATE", 0.2)
SENTRY_IMPORTANT_TRACES_SAMPLE_RATE = env_sample_rate("SENTRY_IMPORTANT_TRACES_SAMPLE_RATE", 1.0)
SENTRY_BACKGROUND_TRACES_SAMPLE_RATE = env_sample_rate("SENTRY_BACKGROUND_TRACES_SAMPLE_RATE", 1.0)
SENTRY_PROFILE_SESSION_SAMPLE_RATE = env_sample_rate("SENTRY_PROFILE_SESSION_SAMPLE_RATE", 0.2)
SENTRY_ENABLE_LOGS = env.bool("SENTRY_ENABLE_LOGS", default=True)
SENTRY_LOG_LEVEL = env_log_level("SENTRY_LOG_LEVEL", logging.WARNING)
SENTRY_BREADCRUMB_LOG_LEVEL = env_log_level("SENTRY_BREADCRUMB_LOG_LEVEL", logging.INFO)
SENTRY_ENABLE_METRICS = env.bool("SENTRY_ENABLE_METRICS", default=True)
SENTRY_SEND_DEFAULT_PII = env.bool("SENTRY_SEND_DEFAULT_PII", default=False)
SENTRY_INCLUDE_LOCAL_VARIABLES = env.bool("SENTRY_INCLUDE_LOCAL_VARIABLES", default=False)
SENTRY_INCLUDE_AI_PROMPTS = env.bool("SENTRY_INCLUDE_AI_PROMPTS", default=False)
SENTRY_STREAM_GEN_AI_SPANS = env.bool("SENTRY_STREAM_GEN_AI_SPANS", default=True)
SENTRY_MAX_REQUEST_BODY_SIZE = env("SENTRY_MAX_REQUEST_BODY_SIZE", default="small")
SENTRY_MAX_VALUE_LENGTH = env.int("SENTRY_MAX_VALUE_LENGTH", default=10000)
SENTRY_TRACE_PROPAGATION_TARGETS = env_csv("SENTRY_TRACE_PROPAGATION_TARGETS", default=[SITE_URL])
SENTRY_STRICT_TRACE_CONTINUATION = env.bool("SENTRY_STRICT_TRACE_CONTINUATION", default=True)
SENTRY_IGNORED_TRANSACTION_PREFIXES = ("/static/", "/media/", "/favicon.ico", "/robots.txt")
SENTRY_IMPORTANT_TRANSACTION_PREFIXES = ("/admin/", "/projects/", "/jobs/post/", "/newsletter/")
SENTRY_BACKGROUND_TRANSACTION_NAMES = (
    "projects.tasks.fetch_page_content",
    "projects.tasks.analyze_project",
    "newsletter.tasks.send_buttondown_newsletter",
    "jobs.tasks.get_latest_jobs_from_tj_alerts",
)
SENTRY_SENSITIVE_LOG_ATTRIBUTE_PARTS = (
    "authorization",
    "cookie",
    "email",
    "ip_address",
    "password",
    "secret",
)
SENTRY_SENSITIVE_LOG_ATTRIBUTE_NAMES = (
    "apitoken",
    "api_token",
    "authtoken",
    "auth_token",
    "accesstoken",
    "access_token",
    "csrf_token",
    "idtoken",
    "id_token",
    "refreshtoken",
    "refresh_token",
    "sessiontoken",
    "session_token",
    "token",
)
SENTRY_SENSITIVE_LOG_ATTRIBUTE_SUFFIXES = (
    ".token",
    "_token",
)


def sentry_sampling_path(sampling_context):
    environ = sampling_context.get("wsgi_environ") or {}
    if environ.get("PATH_INFO"):
        return environ["PATH_INFO"]

    asgi_scope = sampling_context.get("asgi_scope") or {}
    if asgi_scope.get("path"):
        return asgi_scope["path"]

    return ""


def sentry_traces_sampler(sampling_context):
    transaction_context = sampling_context.get("transaction_context") or {}
    transaction_name = transaction_context.get("name") or ""
    op = transaction_context.get("op") or ""
    path = sentry_sampling_path(sampling_context)

    if path.startswith(SENTRY_IGNORED_TRANSACTION_PREFIXES):
        return 0.0

    if op.startswith("queue.") or transaction_name in SENTRY_BACKGROUND_TRANSACTION_NAMES:
        return SENTRY_BACKGROUND_TRACES_SAMPLE_RATE

    if path.startswith(SENTRY_IMPORTANT_TRANSACTION_PREFIXES):
        return SENTRY_IMPORTANT_TRACES_SAMPLE_RATE

    return SENTRY_TRACES_SAMPLE_RATE


def sentry_before_send_log(log, _hint):
    attributes = log.get("attributes")
    if not isinstance(attributes, dict):
        return log

    for key in list(attributes.keys()):
        normalized_key = key.lower().replace("-", "_")
        if (
            normalized_key in SENTRY_SENSITIVE_LOG_ATTRIBUTE_NAMES
            or any(sensitive_part in normalized_key for sensitive_part in SENTRY_SENSITIVE_LOG_ATTRIBUTE_PARTS)
            or any(normalized_key.endswith(suffix) for suffix in SENTRY_SENSITIVE_LOG_ATTRIBUTE_SUFFIXES)
        ):
            attributes[key] = "[Filtered]"

    return log


# Remove the port from the SITE_URL and the https prefix (mostly for dev)
ALLOWED_HOSTS = [SITE_URL.replace("http://", "").replace("https://", "").split(":")[0]]

CSRF_TRUSTED_ORIGINS = [SITE_URL]

ADMIN_URL = env("ADMIN_URL")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "django.contrib.humanize",
    "django.forms",
    "django_extensions",
    "django_component",
    "django_filters",
    "rest_framework",
    "rest_framework.authtoken",
    "anymail",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.twitter",
    "cloudinary",
    "widget_tweaks",
    "django_q",
    "webpack_boilerplate",
    "robots",
    "pages.apps.PagesConfig",
    "projects.apps.ProjectsConfig",
    "jobs.apps.JobsConfig",
    "podcast.apps.PodcastConfig",
    "makers.apps.MakersConfig",
    "blog.apps.BlogConfig",
    "newsletter.apps.NewsletterConfig",
    "users.apps.UsersConfig",
    "api.apps.ApiConfig",
    "developers.apps.DevelopersConfig",
    "tools.apps.ToolsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "posthog.integrations.django.PosthogContextMiddleware",
    "builtwithdjango.analytics.AnalyticsRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "django_structlog.middlewares.RequestMiddleware",  # adds log for each request
]

ROOT_URLCONF = "builtwithdjango.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "builtins": [
                "django_component.templatetags",
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "users.context_processors.available_social_providers",
                "builtwithdjango.analytics.posthog_template_context",
            ],
        },
    },
]

WSGI_APPLICATION = "builtwithdjango.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": env.db_url(),
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/build"),
]

WEBPACK_LOADER = {
    "MANIFEST_FILE": os.path.join(BASE_DIR, "frontend/build/manifest.json"),
}

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

AWS_S3_REGION_NAME = "eu-east-1"
AWS_S3_ENDPOINT_URL = env("AWS_S3_ENDPOINT_URL")
AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = f"bwd-{ENVIRONMENT}"
# AWS_S3_FILE_OVERWRITE = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "default_acl": "public-read",
            "region_name": AWS_S3_REGION_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "querystring_auth": False,
            "file_overwrite": False,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

# Sites
SITE_ID = 1

# Newsletters
EMAILOCTOPUS_API = env("EMAILOCTOPUS_API")
OCTO_LIST_ID = env("OCTO_LIST_ID")
REVUE_API_TOKEN = env("REVUE_API_TOKEN")
BUTTONDOWN_API_TOKEN = env("BUTTONDOWN_API_TOKEN")


INTERNAL_IPS = [
    "127.0.0.1",
]

AUTH_USER_MODEL = "users.CustomUser"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# config/settings.py
LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

ANYMAIL = {
    "MAILGUN_API_KEY": env("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": "mg.builtwithdjango.com",
}

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "mailhog"  # Use the service name from docker-compose
    EMAIL_PORT = 1025
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
else:
    if env("MAILGUN_API_KEY", default="") == "":
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"


DEFAULT_FROM_EMAIL = "Built with Django <rasul@builtwithdjango.com>"
SERVER_EMAIL = "error@builtwithdjango.com"

# Overriding the HTML of Built-In Widgets
# from Two Scoops of Django 3.x
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# django-allauth
# From django for professional book
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

ACCOUNT_FORMS = {
    "login": "users.forms.CustomLoginForm",
    "signup": "users.forms.CustomUserCreationForm",
}

ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_UNIQUE_EMAIL = True
if ENVIRONMENT == "prod":
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"

# Stripe
STRIPE_LIVE_SECRET_KEY = env("STRIPE_LIVE_SECRET_KEY")
STRIPE_TEST_SECRET_KEY = env("STRIPE_TEST_SECRET_KEY")
STRIPE_LIVE_MODE = env.bool("STRIPE_LIVE_MODE")
STRIPE_SECRET_KEY = STRIPE_LIVE_SECRET_KEY if STRIPE_LIVE_MODE else STRIPE_TEST_SECRET_KEY
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_PRO_PRICE_ID = env("STRIPE_PRO_PRICE_ID", default="")
STRIPE_DJANGO_DEVS_PRICE_ID = env("STRIPE_DJANGO_DEVS_PRICE_ID", default="")
STRIPE_JOB_PRICE_ID = env("STRIPE_JOB_PRICE_ID", default="")

# Cloudinary
cloudinary.config(
    cloud_name=env("CLOUDINARY_CLOUD_NAME"), api_key=env("CLOUDINARY_API_KEY"), api_secret=env("CLOUDINARY_API_SECRET")
)

# django-q
Q_CLUSTER = {
    "name": "builtwithdjango-q",
    "timeout": 90,
    "retry": 120,
    "workers": 4,
    "max_attempts": 2,
    "redis": env("REDIS_URL"),
    "error_reporter": {},
}

# Screenshot API
SCREENSHOT_API_KEY = env("SCREENSHOT_API_KEY")


def extract_from_record(logger, name, event_dict):
    """
    Extract thread name and add them to the event dict.
    """
    record = event_dict["_record"]
    event_dict["thread_id"] = record.thread
    return event_dict


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(levelname)s %(message)s"},
        "verbose": {"format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"},
        "json": {"format": "%(message)s"},
        "json_formatter": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processors": [
                extract_from_record,
                structlog.stdlib.ProcessorFormatter.remove_processors_meta,
                structlog.processors.JSONRenderer(),
            ],
        },
        "plain_console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
        "key_value": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.KeyValueRenderer(key_order=["timestamp", "level", "event", "logger"]),
        },
    },
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "prod_console": {
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
            "level": "DEBUG",
        },
        "json_console": {
            "class": "logging.StreamHandler",
            "formatter": "json_formatter",
            "level": "DEBUG",
        },
    },
    "loggers": {
        "django_structlog": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
        # django.server can log some low-level logs, but also does log requests,
        # for some reason...
        "django.server": {
            "handlers": ["console"],
            "level": "CRITICAL",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",  # so we don't chunder 404s, etc
            "propagate": False,
        },
        "builtwithdjango": {
            "level": "DEBUG",
            "handlers": ["console"],
            "propagate": False,
        },
    },
}

structlog_processors = [
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.filter_by_level,
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.stdlib.add_logger_name,
    structlog.stdlib.add_log_level,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.StackInfoRenderer(),
    # structlog.processors.format_exc_info,
]

if SENTRY_ENABLED:
    structlog_processors.append(
        SentryProcessor(
            event_level=logging.ERROR,
            level=logging.INFO,
            active=True,
            as_context=True,
            tag_keys="__all__",
            verbose=True,
        )
    )

if LOGFIRE_TOKEN:
    structlog_processors.append(logfire.StructlogProcessor())

structlog_processors.extend(
    [
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]
)

structlog.configure(
    processors=structlog_processors,
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)

if ENVIRONMENT == "prod":
    LOGGING["loggers"]["django.server"]["level"] = "WARNING"
    LOGGING["loggers"]["django_structlog"]["handlers"].append("json_console")
    LOGGING["loggers"]["builtwithdjango"]["level"] = env("DJANGO_LOG_LEVEL", default="INFO")
    LOGGING["loggers"]["builtwithdjango"]["handlers"].append("json_console")

if SENTRY_ENABLED:
    Q_CLUSTER["error_reporter"]["sentry"] = {"dsn": SENTRY_DSN}
    sentry_sdk.init(
        debug=DEBUG,
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        release=SENTRY_RELEASE,
        dist=SENTRY_DIST,
        server_name=SENTRY_SERVER_NAME,
        sample_rate=SENTRY_ERROR_SAMPLE_RATE,
        send_default_pii=SENTRY_SEND_DEFAULT_PII,
        traces_sampler=sentry_traces_sampler,
        profile_session_sample_rate=SENTRY_PROFILE_SESSION_SAMPLE_RATE,
        profile_lifecycle="trace",
        integrations=[
            DjangoIntegration(
                middleware_spans=True,
                signals_spans=True,
            ),
            RedisIntegration(),
            LoggingIntegration(
                level=SENTRY_BREADCRUMB_LOG_LEVEL,
                event_level=None,
                sentry_logs_level=SENTRY_LOG_LEVEL,
            ),
            PydanticAIIntegration(
                include_prompts=SENTRY_INCLUDE_AI_PROMPTS,
                handled_tool_call_exceptions=True,
            ),
        ],
        attach_stacktrace=True,
        include_local_variables=SENTRY_INCLUDE_LOCAL_VARIABLES,
        max_request_body_size=SENTRY_MAX_REQUEST_BODY_SIZE,
        max_value_length=SENTRY_MAX_VALUE_LENGTH,
        enable_logs=SENTRY_ENABLE_LOGS,
        before_send_log=sentry_before_send_log,
        enable_metrics=SENTRY_ENABLE_METRICS,
        stream_gen_ai_spans=SENTRY_STREAM_GEN_AI_SPANS,
        trace_propagation_targets=SENTRY_TRACE_PROPAGATION_TARGETS,
        strict_trace_continuation=SENTRY_STRICT_TRACE_CONTINUATION,
        trace_ignore_status_codes={404},
        project_root=BASE_DIR,
        in_app_include=[
            "api",
            "blog",
            "builtwithdjango",
            "developers",
            "jobs",
            "makers",
            "newsletter",
            "pages",
            "podcast",
            "projects",
            "tools",
            "users",
        ],
    )
    sentry_sdk.set_tag("app.process_type", env("APP_PROCESS_TYPE", default="unknown"))

BUILTWITHDJANGO_POSTHOG_PROJECT_API_KEY = "phc_Xvm3S1MGcMQXMHo2VJZabDhNJwmwbyhLedddpIU83Mo"
POSTHOG_API_KEY = env(
    "POSTHOG_API_KEY",
    default=BUILTWITHDJANGO_POSTHOG_PROJECT_API_KEY if ENVIRONMENT == "prod" else "",
)
POSTHOG_HOST = env("POSTHOG_HOST", default="https://us.i.posthog.com")
POSTHOG_UI_HOST = env("POSTHOG_UI_HOST", default="https://us.posthog.com")
POSTHOG_PERSONAL_API_KEY = env("POSTHOG_PERSONAL_API_KEY", default="")
POSTHOG_ENABLED = bool(POSTHOG_API_KEY) and env.bool("POSTHOG_ENABLED", default=ENVIRONMENT == "prod")
POSTHOG_JS_DEFAULTS = "2026-01-30"

posthog.api_key = POSTHOG_API_KEY
posthog.project_api_key = POSTHOG_API_KEY
posthog.host = POSTHOG_HOST
posthog.personal_api_key = POSTHOG_PERSONAL_API_KEY or None
posthog.debug = DEBUG
posthog.disabled = not POSTHOG_ENABLED
posthog.disable_geoip = False
posthog.enable_exception_autocapture = True
posthog.capture_exception_code_variables = True
posthog.code_variables_mask_patterns = [
    r"(?i)password",
    r"(?i)secret",
    r"(?i)passwd",
    r"(?i)pwd",
    r"(?i)api_key",
    r"(?i)apikey",
    r"(?i)auth",
    r"(?i)credentials",
    r"(?i)privatekey",
    r"(?i)private_key",
    r"(?i)token",
    r"(?i)aws_access_key_id",
    r"(?i)_pass",
    r"(?i)sk_",
    r"(?i)jwt",
    r"(?i)dsn",
    r"(?i)cookie",
    r"(?i)session",
    r"(?i)stripe",
    r"(?i)card",
]
posthog.code_variables_ignore_patterns = [r"^__.*"]
posthog.before_send = posthog_before_send
posthog.super_properties = {
    "app": "builtwithdjango",
    "environment": ENVIRONMENT,
}
posthog.enable_keep_alive()
POSTHOG_MW_EXTRA_TAGS = posthog_extra_tags
POSTHOG_MW_REQUEST_FILTER = posthog_request_filter
POSTHOG_MW_CAPTURE_EXCEPTIONS = POSTHOG_ENABLED

if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": env("REDIS_URL"),
        }
    }

TJ_ALERTS_HOST = "https://gettjalerts.com/api"
TJ_ALERTS_API_KEY = env("TJ_ALERTS_API_KEY")

HEALTHCHECKS_HOST = "https://healthchecks.cr.lvtd.dev/ping"

JINA_READER_API_KEY = env("JINA_READER_API_KEY")
JINA_READER_BASE_URL = "https://r.jina.ai"

OPENROUTER_API_KEY = env("OPENROUTER_API_KEY")
PYDANTIC_AI_MODEL = env("PYDANTIC_AI_MODEL", default="openrouter:deepseek/deepseek-v4-flash")

READWISE_API_TOKEN = env("READWISE_API_TOKEN")
